// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPSrlw7LtApMRhIlPYiQkFw3xKBPXWr3E',
    appId: '1:671273452701:web:e100424f8c33f36e7e4074',
    messagingSenderId: '671273452701',
    projectId: 'shivam-resorts',
    authDomain: 'shivam-resorts.firebaseapp.com',
    storageBucket: 'shivam-resorts.firebasestorage.app',
    measurementId: 'G-LD79FPXQT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-FWwyBtRY9gIqnYVhL81w8DiXvPuYNg',
    appId: '1:671273452701:android:2c3a23fd623be16b7e4074',
    messagingSenderId: '671273452701',
    projectId: 'shivam-resorts',
    storageBucket: 'shivam-resorts.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSrlw7LtApMRhIlPYiQkFw3xKBPXWr3E',
    appId: '1:671273452701:web:b3141687489fab6d7e4074',
    messagingSenderId: '671273452701',
    projectId: 'shivam-resorts',
    authDomain: 'shivam-resorts.firebaseapp.com',
    storageBucket: 'shivam-resorts.firebasestorage.app',
    measurementId: 'G-4KG9TKB5LX',
  );
}